kind: Deployment
apiVersion: apps/v1
metadata:
  name: lab2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab2
  template:
    metadata:
      labels:
        app: lab2
    spec:
      containers:
      - name: hello-world
        image: strm/helloworld-http


