name: Publish to dockerhub (with Hashicorp Vault)

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: "/lab3/files"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hashicorp Vault secrets import
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: http://127.0.0.1:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/dockerhub DOCKERHUB_USERNAME ;
            secret/data/dockerhub DOCKERHUB_ACCESS_TOKEN

      - name: DH login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push to DH
        uses: docker/build-push-action@v5
        with:
          context: ./lab3/files/
          push: true
          tags: guseynovgm/lab3:lab3_star , guseynovgm/lab3:latest
